# Generated by Django 3.1.3 on 2021-01-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answer_db3',
        ),
        migrations.DeleteModel(
            name='answer_db4',
        ),
    ]
