# Generated by Django 3.1.3 on 2021-01-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20210105_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(max_length=60)),
                ('q_id', models.CharField(max_length=200)),
                ('q_value', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'docs_question_suggest',
            },
        ),
    ]
