# Generated by Django 3.1.3 on 2021-01-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20210105_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_db',
            name='question_type',
            field=models.CharField(max_length=30),
        ),
    ]
