# Generated by Django 3.1.3 on 2021-02-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20210111_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=10)),
                ('prob_free', models.CharField(max_length=300)),
                ('prob_category', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
    ]
